--PKS--

ALTER TABLE Clientes 
ADD CONSTRAINT PK_CLIENTES 
PRIMARY KEY(documento);

ALTER TABLE Ubicaciones 
ADD CONSTRAINT PK_UBICACIONES 
PRIMARY KEY(direccion);

ALTER TABLE Versiones
ADD CONSTRAINT PK_VERSIONES
PRIMARY KEY(idVersion);

ALTER TABLE Fotos
ADD CONSTRAINT PK_FOTOS
PRIMARY KEY(url);

ALTER TABLE EventosDeportivos
ADD CONSTRAINT PK_EVENTO
PRIMARY KEY(idEvento);

ALTER TABLE Sedes
ADD CONSTRAINT PK_SEDES
PRIMARY KEY ( idSede);

ALTER TABLE Registros
ADD CONSTRAINT PK_REGISTROS
PRIMARY KEY (version,cliente);


