--CRUDE--
CREATE OR REPLACE PACKAGE PC_MUSICO IS
	PROCEDURE AD_MUSICO(xm_name IN VARCHAR2,xborn in DATE,xdied IN DATE,xborn_in IN VARCHAR2,xliving_in IN VARCHAR2);
	PROCEDURE MOD_MUSICO(xm_no IN NUMBER,xdied IN DATE, xliving_in IN VARCHAR2);
	PROCEDURE EL_MUSICO(xm_no IN NUMBER);
	PROCEDURE CO_MUSICO(xm_no IN NUMBER);
	FUNCTION CO_MUSICOS_CIUDAD RETURN SYS_REFCURSOR;
	FUNCTION CO_MUSICOS_UNIVERSIDAD RETURN XMLTYPE;
	FUNCTION CO_MUSICOS_PREMIADOS RETURN XMLTYPE;
END PC_MUSICO;
	
	
	