--CRUDE--    
CREATE OR REPLACE PACKAGE PC_MUSICO IS
	PROCEDURE AD_MUSICO(xm_name IN VARCHAR2,xborn in DATE,xdied IN DATE,xborn_in IN VARCHAR2,xliving_in IN VARCHAR2, xdetalles IN XMLTYPE );
	PROCEDURE MOD_MUSICO(xm_no IN NUMBER,xdied IN DATE, xliving_in IN VARCHAR2);
	PROCEDURE EL_MUSICO(xm_no IN NUMBER);
	FUNCTION CO_MUSICO RETURN XMLTYPE;
	FUNCTION CO_MUSICOS_CIUDAD (xciudad IN VARCHAR2) RETURN SYS_REFCURSOR;
	FUNCTION CO_MUSICOS_UNIVERSIDAD RETURN SYS_REFCURSOR;
	FUNCTION CO_MUSICOS_PREMIADOS RETURN SYS_REFCURSOR;
END PC_MUSICO;
/
CREATE OR REPLACE PACKAGE PC_COMPOSICION IS
	PROCEDURE AD_COMPOSICION(xc_no IN NUMBER , xcomp_date IN DATE,xc_title IN VARCHAR2,xc_in IN NUMBER);
    FUNCTION CO_COMPOSICION(xc_no IN NUMBER) RETURN  SYS_REFCURSOR;
	FUNCTION CO_COMPOSICION_BANDAS RETURN SYS_REFCURSOR;
END PC_COMPOSICION;
	
	
	


	
	