CREATE OR REPLACE PACKAGE BODY PA_MUSICO IS
	PROCEDURE AD_MUSICO(xm_name IN VARCHAR2,xborn in DATE,xdied IN DATE,xborn_in IN VARCHAR2,xliving_in IN VARCHAR2 , xdetalles XMLTYPE) IS
	BEGIN
		PC_MUSICO.AD_MUSICO(xm_name ,xborn,xdied,xborn_in,xliving_in, xdetalles);
	END;
    PROCEDURE MOD_MUSICO(xm_no IN NUMBER,xdied IN DATE, xliving_in IN VARCHAR2) IS
	BEGIN
        PC_MUSICO.MOD_MUSICO(xm_no,xdied, xliving_in);
	END;
    PROCEDURE EL_MUSICO(xm_no IN NUMBER) IS
	BEGIN 
		PC_MUSICO.EL_MUSICO(xm_no);
	END;
    FUNCTION CO_MUSICO RETURN XMLTYPE IS CO_XML XMLTYPE;
	BEGIN	
		CO_XML := PC_MUSICO.CO_MUSICO;
		RETURN CO_XML;
	END;
    FUNCTION CO_MUSICOS_CIUDAD (xciudad in VARCHAR2) RETURN SYS_REFCURSOR IS  MUSICOSCIUDAD SYS_REFCURSOR;
	BEGIN 
		MUSICOSCIUDAD := PC_MUSICO.CO_MUSICOS_CIUDAD(xciudad);
		RETURN MUSICOSCIUDAD;
	END;
    FUNCTION CO_MUSICOS_UNIVERSIDAD RETURN SYS_REFCURSOR IS MUSICOSUNIVERSIDAD SYS_REFCURSOR;
	BEGIN 
		MUSICOSUNIVERSIDAD := PC_MUSICO.CO_MUSICOS_UNIVERSIDAD;
		RETURN MUSICOSUNIVERSIDAD;
	END;
    FUNCTION CO_MUSICOS_PREMIADOS RETURN SYS_REFCURSOR IS MUSICOSPREMIADOS SYS_REFCURSOR;
	BEGIN
		MUSICOSPREMIADOS := PC_MUSICO.CO_MUSICOS_PREMIADOS;
		RETURN MUSICOSPREMIADOS;
	END;
END PA_MUSICO;            
/

CREATE OR REPLACE PACKAGE BODY PA_ADMINISTRADOR IS
    FUNCTION CO_MUSICOS_PREMIADOS RETURN SYS_REFCURSOR IS MUSICOSPREMIADOS SYS_REFCURSOR;
	BEGIN
		MUSICOSPREMIADOS := PC_MUSICO.CO_MUSICOS_PREMIADOS;
		RETURN MUSICOSPREMIADOS;
	END;
    FUNCTION CO_COMPOSICION_BANDAS RETURN SYS_REFCURSOR IS CO_COM SYS_REFCURSOR;
    BEGIN
        CO_COM := PC_COMPOSICION.CO_COMPOSICION_BANDAS;
        RETURN CO_COM;
    END;
END PA_ADMINISTRADOR;            
/
